# Generated by Django 4.2.1 on 2023-06-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=32)),
                ('rut', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=32)),
                ('mensaje', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('html_body', models.CharField(max_length=4096)),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('id_compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.compania')),
            ],
        ),
    ]
