# Generated by Django 4.2.1 on 2023-06-24 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 24, 0, 18, 54, 993183, tzinfo=datetime.timezone.utc), verbose_name='Fecha Registro'),
            preserve_default=False,
        ),
    ]
