# Generated by Django 4.2.1 on 2023-06-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_mensaje_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.CharField(default='Anonimo', max_length=255),
        ),
    ]
