# Generated by Django 4.2.1 on 2023-06-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_articulo_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Anonimo', max_length=100)),
                ('mensaje', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.articulo')),
            ],
        ),
    ]
