# Generated by Django 4.2.1 on 2023-06-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_remove_mensaje_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='articleImage',
            field=models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='ImagenArticulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='headerImage',
            field=models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='ImagenHeader'),
        ),
    ]
